services:
  db:
    image: postgres:16
    container_name: postgres_referat
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: referat_db
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      # 10.80.0.40 este IP-ul de la VPS prin conexiune Wireguard VPN
      - "10.80.0.40:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./conf/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]

volumes:
  db_data: